name: simoa
channels:
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312he558020_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - contourpy=1.2.0=py312h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py312haa95532_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=hd77b12b_0
  - fonttools=4.51.0=py312h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.28.0=py312haa95532_0
  - ipython=8.25.0=py312haa95532_0
  - jedi=0.19.1=py312haa95532_0
  - joblib=1.4.2=py312haa95532_0
  - jpeg=9e=h827c3e9_2
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_core=5.7.2=py312haa95532_0
  - kiwisolver=1.4.4=py312hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.8=py312h2bbff1b_0
  - mkl_random=1.2.4=py312h59b6b97_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - numexpr=2.8.7=py312h96b7d27_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openjpeg=2.4.0=h4afccc4_2
  - openpyxl=3.1.2=py312h2bbff1b_0
  - openssl=3.0.15=h827c3e9_0
  - packaging=24.1=py312haa95532_0
  - pandas=2.2.2=py312h0158946_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.6=py312haa95532_0
  - pillow=10.4.0=py312h827c3e9_0
  - pip=24.0=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - plotly=5.22.0=py312hfc267ef_0
  - ply=3.11=py312haa95532_1
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pygments=2.15.1=py312haa95532_1
  - pyparsing=3.0.9=py312haa95532_0
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - python=3.12.4=h14ffc60_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pyzmq=25.1.2=py312hd77b12b_0
  - qt-main=5.15.2=h19c9488_10
  - scikit-learn=1.5.1=py312h0158946_0
  - scipy=1.13.1=py312hbb039d4_0
  - seaborn=0.13.2=py312haa95532_0
  - setuptools=69.5.1=py312haa95532_0
  - sip=6.7.12=py312hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.2=py312h4b0e54e_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=8.2.3=py312haa95532_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.1=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - vc=14.2=h2eaa2aa_4
  - vs2015_runtime=14.29.30133=h43f2093_4
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py312haa95532_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
    - adjusttext==1.2.0
    - altgraph==0.17.4
    - auto-py-to-exe==2.46.0
    - bioinfokit==2.1.4
    - bottle==0.13.2
    - bottle-websocket==0.2.9
    - cabarchive==0.2.4
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - cryptography==44.0.3
    - cx-freeze==8.1.0
    - cx-logging==3.2.1
    - eel==0.18.1
    - filelock==3.18.0
    - fire==0.7.0
    - future==1.0.0
    - gevent==25.4.1
    - gevent-websocket==0.10.1
    - greenlet==3.2.0
    - h5py==3.12.1
    - idna==3.10
    - imbalanced-learn==0.13.0
    - lief==0.16.4
    - lxml==5.4.0
    - matplotlib==3.9.2
    - matplotlib-venn==1.1.1
    - opencv-python-headless==4.11.0.86
    - pathlib==1.0.1
    - pdf2docx==0.5.8
    - pdfminer-six==20250327
    - pdfplumber==0.11.6
    - pefile==2023.2.7
    - pycparser==2.22
    - pyinstaller==6.13.0
    - pyinstaller-hooks-contrib==2025.3
    - pymatreader==1.0.0
    - pymupdf==1.25.5
    - pypdfium2==4.30.1
    - python-docx==1.1.2
    - pyvolcans==1.3.2
    - pywin32-ctypes==0.2.3
    - rapidfuzz==3.10.1
    - requests==2.32.3
    - sklearn-compat==0.1.3
    - striprtf==0.0.29
    - tabulate==0.9.0
    - termcolor==3.1.0
    - textwrap3==0.9.2
    - thefuzz==0.22.1
    - typing-extensions==4.13.2
    - urllib3==2.4.0
    - volcanoplot==0.0.2
    - xmltodict==0.14.2
    - zope-event==5.0
    - zope-interface==7.2
prefix: C:\Users\hbozkurt\.conda\envs\simoa
